import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/*This creates a learn Link on the page that is perssistent accross all pages */}
        <Link href="/learn">
          Learn
        </Link>
        <br />
        
        <Link  href="/again" className="bg-green-900 rounded-xl px-3 py-1 " >again</Link>
            
        {children}
      </body>
    </html>
  );
}
