import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link"
import SideBar from "../components/SideBar";

/* * This is the main layout of the application.
 *It has the side bar component imported and rendered inside the body.
 *Any page rendered inside this layout (with-sidebar) folder will have the side bar component.
*/

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    /*This flexes the entire page and allows for the webpage to be responsive. */
      <div className="flex min-h-screen w-full">
        
        <SideBar/>
        
          {children}
        
        
      </div>
  );
}
