import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link"

/** This is the default layout of the  application
  * Anything rendered inside this layout (without-sidebar) folder will not have the side bar component.
  * The aim of having multiple layouts is to have different pages with and without the side bar component.
  * For example, the learn page has the side bar component, but exercise pages will not.
*/

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
   {children}
      </body>
    </html>
  );
}
