import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import SignOutButton from "./components/SignOutButton";
export const dynamic = 'force-dynamic';

/**
 * This is the default layout of the application.
 * The aim of having multiple layouts is to have different pages with and without the side bar component.
 * For example, the learn page has the side bar component, but exercise pages will not.
 * Any other layouts will have this layout plus an additional component.
 */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodePal",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 🔹 Create the Supabase server client using cookies
  const supabase = createServerComponentClient({ cookies });

  // 🔹 Get the current session (user info, access token, etc.)
  const {
    data: { session },
  } = await supabase.auth.getSession();

  // You can now access `session?.user` for user data, or pass it to context/providers
  const user = session?.user;

  return (
    <html lang="en">
<body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col bg-gray-800`}>

  {/* Navbar with outside margin */}
  <div className="p-4 bg-gray-800">
    <nav className="bg-gray-700 text-white px-6 py-4 flex justify-between items-center min-w-[600px] rounded-3xl border border-gray-700">
      <Link className="bg-gray-300 p-4 rounded-xl text-gray-900 font-bold hover:bg-gray-500 transition-all duration-400 shadow-xl shadow-gray-900/100" href="/">CodePal</Link>
      <div className="space-x-10">
        {user ? (
          <>
            <span className="">Hello {user.email}!</span>
            <SignOutButton />
          </>
        ) : (
          <Link href="/login" className="underline bg-gray-300 p-4 rounded-xl text-gray-900 font-bold hover:bg-gray-500 transition-all duration-400 shadow-xl shadow-gray-900/100">
            Sign In
          </Link>
        )}
      </div>
    </nav>
  </div>

  <main className="flex-1">
    {children}
  </main>
</body>
    </html>
  );
}
