import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
export const dynamic = 'force-dynamic';

/**
 * This is the default layout of the application.
 * The aim of having multiple layouts is to have different pages with and without the side bar component.
 * For example, the learn page has the side bar component, but exercise pages will not.
 * Any other layouts will have this layout plus an additional component.
 */

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CodePal",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // 🔹 Create the Supabase server client using cookies
  const supabase = createServerComponentClient({ cookies });

  // 🔹 Get the current session (user info, access token, etc.)
  const {
    data: { session },
  } = await supabase.auth.getSession();

  // You can now access `session?.user` for user data, or pass it to context/providers
  const user = session?.user;

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex h-screen bg-gray-300`}
      >
        {/* Optional global navigation */}
        <nav className="absolute top-0 left-0 w-full bg-gray-800 text-white p-4 flex justify-between items-center">
          <Link href="/">CodePal</Link>
          <div>
            {user ? (
              <span className="text-sm">Signed in as {user.email}</span>
            ) : (
              <Link href="/login" className="text-sm underline">
                Sign In
              </Link>
            )}
          </div>
        </nav>

        <main className="w-full pt-16">{children}</main>
      </body>
    </html>
  );
}
